import { NextResponse } from 'next/server';

export async function GET() {
  const blocks = [
    {
      type: 'text',
      name: 'Paragraph',
      description: 'A simple text block for paragraphs and general content',
      icon: '📄',
      category: 'basic',
      inputs: [
        { name: 'content', type: 'string', required: true, description: 'The text content' },
        { name: 'alignment', type: 'select', options: ['left', 'center', 'right'], default: 'left', description: 'Text alignment' },
        { name: 'size', type: 'select', options: ['sm', 'base', 'lg', 'xl'], default: 'base', description: 'Text size' },
      ],
    },
    {
      type: 'heading',
      name: 'Heading',
      description: 'Heading block for titles and section headers',
      icon: '📝',
      category: 'basic',
      inputs: [
        { name: 'content', type: 'string', required: true, description: 'Heading text' },
        { name: 'level', type: 'select', options: [1, 2, 3, 4, 5, 6], default: 2, description: 'Heading level (H1-H6)' },
        { name: 'alignment', type: 'select', options: ['left', 'center', 'right'], default: 'left', description: 'Text alignment' },
      ],
    },
    {
      type: 'image',
      name: 'Image',
      description: 'Display images with optional captions',
      icon: '🖼️',
      category: 'media',
      inputs: [
        { name: 'url', type: 'string', required: true, description: 'Image URL' },
        { name: 'alt', type: 'string', required: true, description: 'Alt text for accessibility' },
        { name: 'caption', type: 'string', description: 'Image caption' },
        { name: 'width', type: 'select', options: ['small', 'medium', 'large', 'full'], default: 'full', description: 'Image width' },
        { name: 'alignment', type: 'select', options: ['left', 'center', 'right'], default: 'center', description: 'Image alignment' },
      ],
    },
    {
      type: 'button',
      name: 'Button',
      description: 'Call-to-action button with customizable styles',
      icon: '🔘',
      category: 'basic',
      inputs: [
        { name: 'text', type: 'string', required: true, description: 'Button text' },
        { name: 'url', type: 'string', required: true, description: 'Button link URL' },
        { name: 'variant', type: 'select', options: ['primary', 'secondary', 'outline'], default: 'primary', description: 'Button style' },
        { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], default: 'md', description: 'Button size' },
        { name: 'alignment', type: 'select', options: ['left', 'center', 'right'], default: 'left', description: 'Button alignment' },
        { name: 'openInNewTab', type: 'boolean', default: false, description: 'Open link in new tab' },
      ],
    },
    {
      type: 'quote',
      name: 'Quote',
      description: 'Blockquote for highlighting quotes and testimonials',
      icon: '💬',
      category: 'basic',
      inputs: [
        { name: 'content', type: 'string', required: true, description: 'Quote text' },
        { name: 'author', type: 'string', description: 'Quote author' },
        { name: 'citation', type: 'string', description: 'Citation or source' },
      ],
    },
    {
      type: 'code',
      name: 'Code',
      description: 'Code block with syntax highlighting',
      icon: '💻',
      category: 'basic',
      inputs: [
        { name: 'code', type: 'string', required: true, description: 'Code content' },
        { name: 'language', type: 'string', description: 'Programming language for syntax highlighting' },
      ],
    },
    {
      type: 'video',
      name: 'Video',
      description: 'Embed video files (MP4, WebM, etc.)',
      icon: '🎬',
      category: 'media',
      inputs: [
        { name: 'url', type: 'string', required: true, description: 'Video file URL' },
        { name: 'caption', type: 'string', description: 'Video caption' },
        { name: 'autoplay', type: 'boolean', default: false, description: 'Auto-play video' },
        { name: 'controls', type: 'boolean', default: true, description: 'Show video controls' },
      ],
    },
    {
      type: 'youtube',
      name: 'YouTube',
      description: 'Embed YouTube videos',
      icon: '📺',
      category: 'media',
      inputs: [
        { name: 'url', type: 'string', required: true, description: 'YouTube video URL' },
        { name: 'caption', type: 'string', description: 'Video caption' },
      ],
    },
    {
      type: 'spacer',
      name: 'Spacer',
      description: 'Add vertical spacing between blocks',
      icon: '↕️',
      category: 'layout',
      inputs: [
        { name: 'height', type: 'select', options: ['sm', 'md', 'lg', 'xl'], default: 'md', description: 'Spacer height' },
      ],
    },
    {
      type: 'divider',
      name: 'Divider',
      description: 'Horizontal divider line',
      icon: '➖',
      category: 'layout',
      inputs: [
        { name: 'style', type: 'select', options: ['solid', 'dashed', 'dotted'], default: 'solid', description: 'Divider style' },
      ],
    },
    {
      type: 'columns',
      name: 'Columns',
      description: 'Multi-column layout container for nested blocks',
      icon: '📐',
      category: 'layout',
      inputs: [
        { name: 'columns', type: 'array', description: 'Array of column objects with width and blocks' },
        { name: 'gap', type: 'select', options: ['sm', 'md', 'lg'], default: 'md', description: 'Gap between columns' },
      ],
    },
    {
      type: 'tabs',
      name: 'Tabs',
      description: 'Tabbed interface for organizing content',
      icon: '🗂️',
      category: 'layout',
      inputs: [
        { name: 'tabs', type: 'array', description: 'Array of tab objects with label and blocks' },
      ],
    },
    {
      type: 'accordion',
      name: 'Accordion',
      description: 'Collapsible sections for FAQs and long content',
      icon: '📋',
      category: 'layout',
      inputs: [
        { name: 'title', type: 'string', description: 'Accordion title' },
        { name: 'items', type: 'array', description: 'Array of accordion items with title and content' },
      ],
    },
    {
      type: 'hero',
      name: 'Hero Section',
      description: 'Large hero banner with title, subtitle, and CTAs',
      icon: '🎯',
      category: 'component',
      inputs: [
        { name: 'title', type: 'string', required: true, description: 'Hero title' },
        { name: 'subtitle', type: 'string', description: 'Hero subtitle' },
        { name: 'description', type: 'string', description: 'Hero description' },
        { name: 'ctaText', type: 'string', description: 'Primary CTA button text' },
        { name: 'ctaLink', type: 'string', description: 'Primary CTA button link' },
        { name: 'secondaryCtaText', type: 'string', description: 'Secondary CTA button text' },
        { name: 'secondaryCtaLink', type: 'string', description: 'Secondary CTA button link' },
        { name: 'backgroundImage', type: 'string', description: 'Background image URL' },
        { name: 'backgroundVideo', type: 'string', description: 'Background video URL' },
      ],
    },
    {
      type: 'cta',
      name: 'Call to Action',
      description: 'Prominent call-to-action section with buttons',
      icon: '📣',
      category: 'component',
      inputs: [
        { name: 'title', type: 'string', required: true, description: 'CTA title' },
        { name: 'description', type: 'string', description: 'CTA description' },
        { name: 'primaryButtonText', type: 'string', required: true, description: 'Primary button text' },
        { name: 'primaryButtonUrl', type: 'string', required: true, description: 'Primary button URL' },
        { name: 'secondaryButtonText', type: 'string', description: 'Secondary button text' },
        { name: 'secondaryButtonUrl', type: 'string', description: 'Secondary button URL' },
        { name: 'backgroundStyle', type: 'select', options: ['gradient', 'solid', 'none'], default: 'gradient', description: 'Background style' },
      ],
    },
    {
      type: 'services-grid',
      name: 'Services Grid',
      description: 'Grid layout for displaying services or features',
      icon: '🎨',
      category: 'component',
      inputs: [
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'services', type: 'array', description: 'Array of service items with title, description, icon, image, and link' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 3, description: 'Number of columns' },
      ],
    },
    {
      type: 'card-grid',
      name: 'Card Grid',
      description: 'Grid of cards for displaying content items',
      icon: '🃏',
      category: 'component',
      inputs: [
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'cards', type: 'array', description: 'Array of card items with title, description, image, icon, and link' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 3, description: 'Number of columns' },
      ],
    },
    {
      type: 'flip-card-grid',
      name: 'Flip Cards',
      description: 'Interactive 3D flip cards that reveal content on hover or click',
      icon: 'flip',
      category: 'component',
      inputs: [
        { name: 'overline', type: 'string', description: 'Small overline text above the title' },
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'cards', type: 'array', description: 'Array of flip cards with front/back content' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 3, description: 'Number of columns' },
        { name: 'flipTrigger', type: 'select', options: ['hover', 'click'], default: 'hover', description: 'Trigger for the flip animation' },
        { name: 'flipAxis', type: 'select', options: ['horizontal', 'vertical'], default: 'horizontal', description: 'Axis of rotation' },
        { name: 'cardHeight', type: 'string', default: '280px', description: 'Card height (CSS unit)' },
        { name: 'accentColor', type: 'string', description: 'Accent color for icons and back face' },
      ],
    },
    {
      type: 'metric-cards',
      name: 'Metric Cards',
      description: 'Case-study-style cards with large metric, label, and institution',
      icon: 'insights',
      category: 'component',
      inputs: [
        { name: 'overline', type: 'string', description: 'Small overline text above the title' },
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'metrics', type: 'array', description: 'Array of metric cards with value, label, institution, and link' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 4, description: 'Number of columns' },
        { name: 'accentColor', type: 'string', description: 'Accent color for metric values and CTAs' },
      ],
    },
    {
      type: 'logo-strip',
      name: 'Logo Strip',
      description: 'A row of client/partner logos with optional overline and grayscale-on-hover styling',
      icon: 'view_column',
      category: 'component',
      inputs: [
        { name: 'overline', type: 'string', description: 'Eyebrow text above the logos' },
        { name: 'logos', type: 'array', description: 'Array of logos with imageUrl, alt, and optional link' },
        { name: 'columns', type: 'select', options: [3, 4, 5, 6, 7, 8], default: 6, description: 'Number of columns' },
        { name: 'grayscale', type: 'boolean', default: true, description: 'Show logos in grayscale, color on hover' },
        { name: 'logoHeight', type: 'string', default: '40px', description: 'Max height of each logo' },
        { name: 'gap', type: 'select', options: ['sm', 'md', 'lg'], default: 'lg', description: 'Spacing between logos' },
        { name: 'alignment', type: 'select', options: ['left', 'center', 'right'], default: 'center', description: 'Alignment on partial rows' },
      ],
    },
    {
      type: 'stats',
      name: 'Statistics',
      description: 'Display key metrics and statistics',
      icon: '📊',
      category: 'component',
      inputs: [
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'stats', type: 'array', description: 'Array of stat items with value and label' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 3, description: 'Number of columns' },
      ],
    },
    {
      type: 'testimonial',
      name: 'Testimonial',
      description: 'Customer testimonial or review',
      icon: '⭐',
      category: 'component',
      inputs: [
        { name: 'quote', type: 'string', required: true, description: 'Testimonial quote' },
        { name: 'author', type: 'string', required: true, description: 'Author name' },
        { name: 'role', type: 'string', description: 'Author role/title' },
        { name: 'company', type: 'string', description: 'Author company' },
        { name: 'avatar', type: 'string', description: 'Author avatar image URL' },
      ],
    },
    {
      type: 'blog-posts',
      name: 'Blog Posts',
      description: 'Display a grid of blog posts from the CMS',
      icon: '📰',
      category: 'component',
      inputs: [
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'postType', type: 'string', description: 'Filter by post type (optional)' },
        { name: 'limit', type: 'number', default: 3, description: 'Number of posts to display' },
        { name: 'showExcerpt', type: 'boolean', default: true, description: 'Show post excerpts' },
        { name: 'columns', type: 'select', options: [2, 3], default: 3, description: 'Number of columns' },
      ],
    },
    {
      type: 'featured-content',
      name: 'Featured Content',
      description: 'Featured content section with image and statistics',
      icon: '✨',
      category: 'component',
      inputs: [
        { name: 'title', type: 'string', required: true, description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'imageUrl', type: 'string', description: 'Featured image URL' },
        { name: 'imagePosition', type: 'select', options: ['left', 'right'], default: 'right', description: 'Image position' },
        { name: 'buttonText', type: 'string', description: 'CTA button text' },
        { name: 'buttonUrl', type: 'string', description: 'CTA button URL' },
        { name: 'stats', type: 'array', description: 'Array of stat items with value and label' },
      ],
    },
    // eCommerce Blocks
    {
      type: 'product-grid',
      name: 'Product Grid',
      description: 'Display a grid of products from your store',
      icon: 'shopping_bag',
      category: 'ecommerce',
      inputs: [
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'categorySlug', type: 'string', description: 'Category slug to filter products' },
        { name: 'sort', type: 'select', options: ['newest', 'price_asc', 'price_desc', 'featured'], default: 'newest', description: 'Sort order' },
        { name: 'limit', type: 'number', default: 6, description: 'Number of products to display' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 3, description: 'Number of columns' },
        { name: 'showPrice', type: 'boolean', default: true, description: 'Show product prices' },
        { name: 'showDescription', type: 'boolean', default: false, description: 'Show product descriptions' },
        { name: 'showCategory', type: 'boolean', default: false, description: 'Show category labels' },
        { name: 'buttonText', type: 'string', description: 'Button text (e.g. Add to Cart)' },
      ],
    },
    {
      type: 'featured-products',
      name: 'Featured Products',
      description: 'Showcase featured products with badges and sale indicators',
      icon: 'star',
      category: 'ecommerce',
      inputs: [
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'limit', type: 'number', default: 4, description: 'Number of products' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 4, description: 'Number of columns' },
        { name: 'showPrice', type: 'boolean', default: true, description: 'Show product prices' },
        { name: 'showBadge', type: 'boolean', default: true, description: 'Show featured badge' },
        { name: 'badgeText', type: 'string', default: 'Featured', description: 'Badge label text' },
        { name: 'buttonText', type: 'string', description: 'Button text (e.g. Shop Now)' },
      ],
    },
    {
      type: 'product-categories',
      name: 'Product Categories',
      description: 'Display product categories as cards or a list',
      icon: 'sell',
      category: 'ecommerce',
      inputs: [
        { name: 'title', type: 'string', description: 'Section title' },
        { name: 'description', type: 'string', description: 'Section description' },
        { name: 'columns', type: 'select', options: [2, 3, 4], default: 3, description: 'Number of columns' },
        { name: 'layout', type: 'select', options: ['grid', 'list'], default: 'grid', description: 'Category layout' },
        { name: 'showProductCount', type: 'boolean', default: true, description: 'Show number of products' },
        { name: 'showImage', type: 'boolean', default: true, description: 'Show category images' },
      ],
    },
    {
      type: 'shopping-cart',
      name: 'Shopping Cart',
      description: 'Shopping cart widget — full, mini, or icon-only',
      icon: 'shopping_cart',
      category: 'ecommerce',
      inputs: [
        { name: 'variant', type: 'select', options: ['full', 'mini', 'icon-only'], default: 'full', description: 'Cart display style' },
        { name: 'showSubtotal', type: 'boolean', default: true, description: 'Show subtotal' },
        { name: 'checkoutButtonText', type: 'string', default: 'Proceed to Checkout', description: 'Checkout button text' },
        { name: 'emptyCartMessage', type: 'string', default: 'Your cart is empty', description: 'Empty cart message' },
      ],
    },
    {
      type: 'store-banner',
      name: 'Store Banner',
      description: 'Promotional banner with discount code and optional countdown',
      icon: 'percent',
      category: 'ecommerce',
      inputs: [
        { name: 'title', type: 'string', required: true, description: 'Banner headline' },
        { name: 'subtitle', type: 'string', description: 'Sub-headline' },
        { name: 'discountCode', type: 'string', description: 'Discount code to display' },
        { name: 'buttonText', type: 'string', description: 'CTA button text' },
        { name: 'buttonUrl', type: 'string', description: 'CTA button link' },
        { name: 'backgroundStyle', type: 'select', options: ['gradient', 'solid', 'image'], default: 'gradient', description: 'Background style' },
        { name: 'backgroundImage', type: 'string', description: 'Background image URL' },
        { name: 'accentColor', type: 'string', description: 'Accent color (hex)' },
        { name: 'countdownDate', type: 'string', description: 'Countdown end date (ISO string)' },
      ],
    },
    {
      type: 'product-detail',
      name: 'Product Detail',
      description: 'Display a single product with images, variants, pricing, and add-to-cart',
      icon: 'package',
      category: 'ecommerce',
      inputs: [
        { name: 'productSlug', type: 'string', required: true, description: 'Product URL slug' },
        { name: 'layout', type: 'select', options: ['standard', 'compact', 'wide'], default: 'standard', description: 'Page layout' },
        { name: 'showGallery', type: 'boolean', default: true, description: 'Show image gallery' },
        { name: 'showDescription', type: 'boolean', default: true, description: 'Show full description' },
        { name: 'showVariants', type: 'boolean', default: true, description: 'Show variant options' },
        { name: 'showAddToCart', type: 'boolean', default: true, description: 'Show add to cart button' },
        { name: 'showBulkPricing', type: 'boolean', default: true, description: 'Show bulk pricing table' },
        { name: 'showBreadcrumb', type: 'boolean', default: true, description: 'Show breadcrumb navigation' },
        { name: 'showTags', type: 'boolean', default: true, description: 'Show tags and SKU' },
      ],
    },
  ];

  return NextResponse.json({
    success: true,
    data: {
      blocks,
      categories: [
        { id: 'basic', name: 'Basic Blocks', description: 'Essential content blocks' },
        { id: 'media', name: 'Media', description: 'Images, videos, and multimedia' },
        { id: 'layout', name: 'Layout', description: 'Structure and organization' },
        { id: 'component', name: 'Components', description: 'Advanced UI components' },
        { id: 'ecommerce', name: 'eCommerce', description: 'Products, cart, and store components' },
      ],
    },
  });
}
