# Configure sponsorship buttons for the repo. Uncomment + fill in the ones you use.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [DanielPCoyle]
# custom: ["https://simplerdevelopment.com"]
