import { preload, preconnect } from 'react-dom';
import { firstContentImageUrls, resolveHtmlRenderCorpus } from '@/lib/blocks/page-fonts';

/**
 * Server component (NO 'use client') that preloads the likely-LCP image into
 * the document <head> as early as possible, plus a preconnect to its origin.
 *
 * Heroes are frequently authored as a CSS background-image (often on an
 * ::after pseudo-element inside an html-render block), which the preload
 * scanner cannot see — so the image otherwise doesn't start loading until the
 * main document JS clears, pushing LCP load-delay to ~6s.
 *
 * Rendering a <link rel=preload> from a CLIENT component in the body is too
 * late (discovered after the head's module preloads). ReactDOM.preload() from
 * a SERVER component is hoisted into <head> and flushed at the very top of the
 * streamed HTML, so the fetch starts immediately. Returns null — it only emits
 * head resource hints.
 */
export function HeroPreload({ content }: { content: string }) {
  // Preload the first couple of on-page images. The LCP element differs by
  // viewport — a small hero photo on desktop, the first full-width grid image
  // on mobile — so covering both candidates keeps the mobile LCP image from
  // sitting undiscovered (lazy, in an html-render block) until the page JS
  // clears. The non-LCP grid cells stay `loading="lazy"`, so these few high-
  // priority preloads don't contend with a dozen eager image requests.
  // Substitute html-render templates FIRST (ITM-031): heroes are authored as
  // url('{{bgImage}}') with the real URL in the block's values dict, so the
  // raw content string never shows a URL next to its mobile-variant reference
  // and pairing below could never fire on templated heroes (which is nearly
  // all of them).
  const corpus = resolveHtmlRenderCorpus(content);
  const urls = firstContentImageUrls(corpus, 2);
  const seenOrigins = new Set<string>();
  for (const url of urls) {
    try {
      if (/^https?:\/\//i.test(url)) {
        const origin = new URL(url).origin;
        if (!seenOrigins.has(origin)) {
          seenOrigins.add(origin);
          // Preconnect to the image origin (no crossOrigin: CSS background-image
          // fetches are not CORS, so a crossorigin hint would open a separate,
          // unused connection).
          preconnect(origin);
        }
      }
    } catch {
      /* ignore malformed URL */
    }
    // When the page's CSS also references a mobile width variant of this
    // image (served under a max-width media query), a plain preload of the
    // full-size URL would DOUBLE-download on phones — the preload fetches
    // 1920px while the CSS fetches the 828px variant. A srcset preload
    // offers both candidates and lets the browser pick the same one the CSS
    // will request (~viewport×DPR: 390×2 → 828; desktop → full). Sizes 100vw
    // matches the full-bleed hero/banner use.
    //
    // Variant convention: `<same path>-w828.webp` — a SIBLING pre-generated
    // asset the import pipeline uploads next to the full-size mirror.
    // Deliberately not a runtime-resize URL: the media-proxy sharp attempt
    // 500'd every image in prod (reverted #64), and Vercel's own /_next/image
    // optimizer is non-functional on this project (400s even for whitelisted
    // static files), so pre-generated bytes are the only resize path that
    // works on this infrastructure.
    const mobileVariant = url.replace(/\.(webp|png|jpe?g|avif)$/i, '-w828.webp');
    if (mobileVariant !== url && corpus.includes(mobileVariant)) {
      preload(url, {
        as: 'image',
        fetchPriority: 'high',
        imageSrcSet: `${mobileVariant} 828w, ${url} 1920w`,
        imageSizes: '100vw',
      });
    } else {
      preload(url, { as: 'image', fetchPriority: 'high' });
    }
  }
  return null;
}
