// Per-block element catalog driving the Elements tab in BlockSettings.
export const ELEMENT_DEFINITIONS: Record<string, { key: string; label: string }[]> = {
  'hero': [
    { key: 'title', label: 'Title' },
    { key: 'subtitle', label: 'Subtitle' },
    { key: 'description', label: 'Description' },
    { key: 'cta', label: 'Primary Button' },
    { key: 'secondaryCta', label: 'Secondary Button' },
  ],
  'hero-slideshow': [
    { key: 'title', label: 'Slide Title' },
    { key: 'subtitle', label: 'Slide Subtitle' },
    { key: 'description', label: 'Slide Description' },
    { key: 'cta', label: 'Primary Button' },
    { key: 'secondaryCta', label: 'Secondary Button' },
    { key: 'statValue', label: 'Stat Value' },
    { key: 'statLabel', label: 'Stat Label' },
  ],
  'cta': [
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'primaryButton', label: 'Primary Button' },
    { key: 'secondaryButton', label: 'Secondary Button' },
  ],
  'card-grid': [
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
    { key: 'card', label: 'Card Container' },
    { key: 'cardTitle', label: 'Card Title' },
    { key: 'cardDescription', label: 'Card Description' },
    { key: 'cardIcon', label: 'Card Icon' },
    { key: 'cardLink', label: 'Card Link' },
    { key: 'cardImage', label: 'Card Image' },
  ],
  'stats': [
    { key: 'title', label: 'Section Title' },
    { key: 'statValue', label: 'Stat Value' },
    { key: 'statLabel', label: 'Stat Label' },
  ],
  'testimonial': [
    { key: 'quoteIcon', label: 'Decorative Quote Icon' },
    { key: 'quote', label: 'Quote Text' },
    { key: 'author', label: 'Author Name' },
  ],
  'services-grid': [
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
    { key: 'card', label: 'Service Card Container' },
    { key: 'serviceTitle', label: 'Service Title' },
    { key: 'serviceDescription', label: 'Service Description' },
    { key: 'serviceIcon', label: 'Service Icon' },
    { key: 'serviceLink', label: 'Service Link' },
    { key: 'serviceImage', label: 'Service Image' },
    { key: 'bullet', label: 'Bullet Item' },
  ],
  'featured-content': [
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'button', label: 'Button' },
    { key: 'statValue', label: 'Stat Value' },
    { key: 'statLabel', label: 'Stat Label' },
  ],
  'quote': [
    { key: 'quoteText', label: 'Quote Text' },
    { key: 'author', label: 'Author' },
  ],
  'blog-posts': [
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
    { key: 'postTitle', label: 'Post Title' },
    { key: 'postExcerpt', label: 'Post Excerpt' },
  ],
  'accordion': [
    { key: 'title', label: 'Section Title' },
    { key: 'itemTitle', label: 'Item Title' },
    { key: 'itemContent', label: 'Item Content' },
  ],
  'tabs': [
    { key: 'tab', label: 'Tab Button (default)' },
    { key: 'activeTab', label: 'Tab Button (active)' },
    { key: 'tabPanel', label: 'Tab Panel' },
  ],
  'gallery': [
    { key: 'caption', label: 'Image Caption' },
  ],
  'image': [
    { key: 'caption', label: 'Image Caption' },
  ],
  'store-banner': [
    { key: 'title', label: 'Title' },
    { key: 'subtitle', label: 'Subtitle' },
    { key: 'discountCode', label: 'Discount Code' },
    { key: 'button', label: 'Button' },
  ],
  'product-detail': [
    { key: 'breadcrumb', label: 'Breadcrumb' },
    { key: 'gallery', label: 'Image Gallery' },
    { key: 'badge', label: 'Sale Badge' },
    { key: 'productName', label: 'Product Name' },
    { key: 'price', label: 'Price' },
    { key: 'comparePrice', label: 'Compare Price' },
    { key: 'shortDescription', label: 'Short Description' },
    { key: 'optionLabel', label: 'Option Label' },
    { key: 'optionButton', label: 'Option Button' },
    { key: 'addToCartButton', label: 'Add to Cart Button' },
    { key: 'sku', label: 'SKU / Tags' },
    { key: 'sectionTitle', label: 'Description Heading' },
  ],
  'product-grid': [
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
  ],
  'featured-products': [
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
  ],
  'product-categories': [
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
  ],
  'booking': [
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  'survey': [
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  'survey-results': [
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  'flip-card-grid': [
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
    { key: 'frontCard', label: 'Card Front' },
    { key: 'frontTitle', label: 'Front Title' },
    { key: 'frontSubtitle', label: 'Front Subtitle' },
    { key: 'frontIcon', label: 'Front Icon' },
    { key: 'backCard', label: 'Card Back' },
    { key: 'backText', label: 'Back Text' },
    { key: 'backLink', label: 'Back Link' },
  ],
  'metric-cards': [
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Section Title' },
    { key: 'description', label: 'Section Description' },
    { key: 'card', label: 'Card Container' },
    { key: 'value', label: 'Metric Value' },
    { key: 'label', label: 'Metric Label' },
    { key: 'institution', label: 'Institution' },
    { key: 'link', label: 'CTA Link' },
  ],
  'logo-strip': [
    { key: 'overline', label: 'Overline' },
    { key: 'logo', label: 'Logo Image' },
  ],
  'timeline': [
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Section Title' },
    { key: 'subtitle', label: 'Section Subtitle' },
    { key: 'stepTitle', label: 'Step Title' },
    { key: 'stepDescription', label: 'Step Description' },
  ],
  'team-showcase': [
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Section Title' },
    { key: 'subtitle', label: 'Section Subtitle' },
    { key: 'memberName', label: 'Member Name' },
    { key: 'memberTitle', label: 'Member Title' },
    { key: 'memberCredentials', label: 'Member Credentials' },
    { key: 'memberBio', label: 'Member Bio' },
    { key: 'specialtyTag', label: 'Specialty Tag' },
  ],
  'bento-grid': [
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Section Title' },
    { key: 'subtitle', label: 'Section Subtitle' },
    { key: 'cardTitle', label: 'Card Title (all variants)' },
    { key: 'cardTitleDark', label: 'Card Title (dark variant only)' },
    { key: 'cardTitleLight', label: 'Card Title (light variant only)' },
    { key: 'cardLead', label: 'Card Lead Text (all variants)' },
    { key: 'cardLeadDark', label: 'Card Lead (dark variant only)' },
    { key: 'cardLeadLight', label: 'Card Lead (light variant only)' },
  ],
  'team-flip-grid': [
    { key: 'memberName', label: 'Member Name' },
    { key: 'memberTitle', label: 'Member Title' },
    { key: 'memberBio', label: 'Member Bio' },
    { key: 'question', label: 'Back: Question' },
    { key: 'answer', label: 'Back: Answer' },
    { key: 'frontCard', label: 'Card Front' },
    { key: 'backCard', label: 'Card Back' },
  ],
  'site-footer': [
    { key: 'logo', label: 'Logo' },
    { key: 'wordmark', label: 'Wordmark' },
    { key: 'tagline', label: 'Tagline' },
    { key: 'linkGroupLabel', label: 'Link Group Label' },
    { key: 'link', label: 'Footer Link' },
    { key: 'socialIcon', label: 'Social Link' },
    { key: 'contactLine', label: 'Contact Line' },
    { key: 'copyright', label: 'Copyright / Disclaimer' },
  ],
  'social-links': [
    { key: 'icon', label: 'Container' },
    { key: 'link', label: 'Link' },
  ],
  'booking-menu': [
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'card', label: 'Card Container' },
    { key: 'cardTitle', label: 'Card Title' },
    { key: 'cardDescription', label: 'Card Description' },
    { key: 'button', label: 'Card CTA / Arrow' },
  ],
};
