import type { AgenticOsDomain, AgenticOsSkill } from './types';

/**
 * Typed projection of `.planning/agentic-os.md`. Every "### `<id>`" block in
 * the Skill details section of that doc maps to exactly one entry here.
 *
 * Do not edit this file to add a skill before updating the doc — the doc is
 * the source of truth and reviewers cross-check against it.
 */
export const SKILLS: readonly AgenticOsSkill[] = [
  // ─── developer-workflow ────────────────────────────────────────────────
  {
    id: 'simplerdev-feature-scaffold',
    domain: 'developer-workflow',
    name: 'SimplerDev Feature Scaffold',
    description:
      'Scaffold a portal-scoped or admin-global CRUD feature: Drizzle schema + REST routes (auth + site resolver + envelope) + e2e helper + Playwright spec.',
    source: { kind: 'repo-skill', path: '.claude/skills/simplerdev-feature-scaffold/SKILL.md' },
    icon: 'build',
    estimatedRuntime: '5-10 min',
    appliesRules: ['envelope-and-resolver', 'tenancy-test', 'no-hand-edit-drizzle', 'use-bun-not-npm'],
    trigger: 'on-demand',
    promptTemplate:
      'Use simplerdev-feature-scaffold to add a new {{scope}} CRUD resource named "{{resource}}" with fields: {{fields}}. Per-id routes: {{withIdRoutes}}. Follow the categories canonical reference exactly. Generate the migration but stop before running db:migrate.',
    variables: [
      { key: 'scope', label: 'Scope (portal-site | portal-client | admin-global)', required: true, placeholder: 'portal-site' },
      { key: 'resource', label: 'Resource name (singular camelCase)', required: true, placeholder: 'serviceArea' },
      { key: 'fields', label: 'Field list (name:type[:modifier])', required: true, placeholder: 'title:varchar(255):required, priority:integer, isActive:boolean:default=true' },
      { key: 'withIdRoutes', label: 'Generate per-id routes?', required: false, placeholder: 'yes' },
    ],
  },
  {
    id: 'simplerdev-ui-scaffold',
    domain: 'developer-workflow',
    name: 'SimplerDev UI Scaffold',
    description:
      'Generate the admin + portal page.tsx layer for an existing CRUD resource — table, inline form, loading state — matching the canonical categories pages.',
    source: { kind: 'repo-skill', path: '.claude/skills/simplerdev-ui-scaffold/SKILL.md' },
    icon: 'dashboard',
    estimatedRuntime: '5-10 min',
    appliesRules: ['material-icons-not-emojis'],
    trigger: 'on-demand',
    promptTemplate:
      'Use simplerdev-ui-scaffold to generate {{surface}} pages for the existing resource "{{resource}}". API base: {{apiBase}}. Read the canonical categories page first and mirror its structure.',
    variables: [
      { key: 'surface', label: 'Surface (admin | portal | both)', required: true, placeholder: 'both' },
      { key: 'resource', label: 'Resource name (must already exist as a CRUD route)', required: true, placeholder: 'serviceArea' },
      { key: 'apiBase', label: 'API base path', required: true, placeholder: '/api/portal/cms/websites/[siteId]/service-areas' },
    ],
  },
  {
    id: 'feature-integrator',
    domain: 'developer-workflow',
    name: 'Feature Integrator',
    description:
      'Compare an external codebase against SimplerDevelopment, produce a gap report, and translate (not copy) missing features into block/API/DB extensions.',
    source: { kind: 'repo-skill', path: '.claude/skills/feature-integrator/SKILL.md' },
    icon: 'compare_arrows',
    estimatedRuntime: '30+ min',
    appliesRules: ['blocks-universal', 'tenancy-test'],
    trigger: 'on-demand',
    promptTemplate:
      'Use feature-integrator to compare the external app at "{{sourcePath}}" against SimplerDevelopment2026. Focus area: {{focusArea}}. Produce a gap report, wait for my approval, then implement {{implementScope}}.',
    variables: [
      { key: 'sourcePath', label: 'Absolute path to the external app source', required: true, placeholder: '../booking-app' },
      { key: 'focusArea', label: 'Domain to compare (booking, chat, content, all)', required: true, placeholder: 'booking' },
      { key: 'implementScope', label: 'What to implement after the report (full-gaps-only | full-and-partial | nothing)', required: false, placeholder: 'full-gaps-only' },
    ],
  },
  {
    id: 'project-orchestrator',
    domain: 'developer-workflow',
    name: 'Project Orchestrator (subagent)',
    description:
      'Multi-step project planner that decomposes a large request into discrete subagent calls and gates each step on the previous output.',
    source: { kind: 'subagent', name: 'project-orchestrator' },
    icon: 'account_tree',
    estimatedRuntime: '30+ min',
    trigger: 'on-demand',
    promptTemplate:
      'Delegate to project-orchestrator. Goal: {{goal}}. Constraints: {{constraints}}. Use sub-skills as needed (simplerdev-feature-scaffold, simplerdev-ui-scaffold, e2e-writer). Gate each step on the previous output and report before merging.',
    variables: [
      { key: 'goal', label: 'Goal in one sentence', required: true, placeholder: 'Ship the service-areas feature end to end' },
      { key: 'constraints', label: 'Constraints (style, scope, deadlines)', required: false, placeholder: 'Portal-only, no admin UI, must pass test:tenancy' },
    ],
  },
  {
    id: 'security-auditor',
    domain: 'developer-workflow',
    name: 'Security Auditor (subagent)',
    description:
      'Reviews pending changes for auth bypasses, leaked secrets, IDOR, and tenant-boundary violations. Wraps the /security-review command.',
    source: { kind: 'subagent', name: 'security-auditor' },
    icon: 'shield',
    estimatedRuntime: '5-10 min',
    appliesRules: ['tenancy-test'],
    trigger: 'on-demand',
    promptTemplate:
      'Use security-auditor to review pending changes on the current branch. Focus: {{focus}}. Flag auth bypasses, IDOR, secret leaks, and tenancy violations. Output a triaged punch list.',
    variables: [
      { key: 'focus', label: 'Optional focus area (auth | tenancy | secrets | all)', required: false, placeholder: 'all' },
    ],
  },

  // ─── cms-blocks ────────────────────────────────────────────────────────
  {
    id: 'simplerdev-block-type',
    domain: 'cms-blocks',
    name: 'SimplerDev Block Type Scaffold',
    description:
      'Scaffold a new block type in lockstep across all 5 integration points: types, render component, registry, BlockRenderer switch, /api/blocks metadata. Enforces the "blocks are universal" rule.',
    source: { kind: 'repo-skill', path: '.claude/skills/simplerdev-block-type/SKILL.md' },
    icon: 'extension',
    estimatedRuntime: '10-20 min',
    appliesRules: ['blocks-universal', 'material-icons-not-emojis'],
    trigger: 'on-demand',
    promptTemplate:
      'Use simplerdev-block-type to scaffold a new block "{{typeKey}}" ({{displayName}}). Category: {{category}}. Material icon: {{icon}}. Fields: {{fields}}. Mirror StatsBlockRender as the reference. Refuse if the block is client-specific.',
    variables: [
      { key: 'typeKey', label: 'Type key (kebab-case)', required: true, placeholder: 'pricing-cards' },
      { key: 'displayName', label: 'Display name', required: true, placeholder: 'Pricing Cards' },
      { key: 'category', label: 'Category (basic|media|layout|component|ecommerce|form|email)', required: true, placeholder: 'component' },
      { key: 'icon', label: 'Material Symbols icon name', required: true, placeholder: 'payments' },
      { key: 'fields', label: 'Field schema', required: true, placeholder: 'title:string, tiers:Tier[], ctaText:string' },
    ],
  },
  {
    id: 'html-render-block',
    domain: 'cms-blocks',
    name: 'HTML-Render Block JSON Editor',
    description:
      "User-invocable. Edit, translate, rename, or validate an html-render block JSON copy/pasted out of the portal's Full Block JSON panel. Returns the complete edited JSON ready to paste back.",
    source: { kind: 'repo-skill', path: '.claude/skills/html-render-block/SKILL.md' },
    icon: 'code',
    estimatedRuntime: '1-3 min',
    trigger: 'on-demand',
    promptTemplate:
      'Edit this html-render block JSON. Operation: {{operation}}. Details: {{details}}. Return the complete block JSON in a single fenced code block, preserving all unknown keys. JSON:\n\n{{blockJson}}',
    variables: [
      { key: 'operation', label: 'Operation (edit-copy | translate | rename-field | add-item | edit-html | validate)', required: true, placeholder: 'edit-copy' },
      { key: 'details', label: 'Operation specifics', required: true, placeholder: "Change headline to 'Stop guessing, start deciding.'" },
      { key: 'blockJson', label: 'Pasted block JSON from the portal panel', required: true, placeholder: '{ "version": 1, "type": "html-render", ... }', type: 'textarea' },
    ],
  },
  {
    id: 'block-orchestrator',
    domain: 'cms-blocks',
    name: 'Block Orchestrator (subagent)',
    description:
      'Drives a multi-block audit pass — picks blocks, dispatches block-implementer per fix, commits one block per commit.',
    source: { kind: 'subagent', name: 'block-orchestrator' },
    icon: 'auto_awesome_motion',
    estimatedRuntime: '30+ min',
    appliesRules: ['blocks-universal', 'one-block-per-commit'],
    trigger: 'on-demand',
    promptTemplate:
      "Use block-orchestrator to drive a block audit pass. Audit scope: {{scope}}. For each finding, dispatch block-implementer. Commit one block per commit. Stop after {{maxBlocks}} blocks or when the audit is clean.",
    variables: [
      { key: 'scope', label: "Audit scope (e.g. 'all blocks missing responsive props', 'all blocks using emoji icons')", required: true, placeholder: 'all blocks missing elementStyles support' },
      { key: 'maxBlocks', label: 'Max blocks to touch in this pass', required: false, placeholder: '10' },
    ],
  },
  {
    id: 'block-implementer',
    domain: 'cms-blocks',
    name: 'Block Implementer (subagent)',
    description:
      'One-off block fix: applies a specific change to a single block type and verifies render + editor parity.',
    source: { kind: 'subagent', name: 'block-implementer' },
    icon: 'handyman',
    estimatedRuntime: '5-10 min',
    appliesRules: ['blocks-universal', 'one-block-per-commit'],
    trigger: 'on-demand',
    promptTemplate:
      'Use block-implementer to apply this fix to block "{{blockType}}": {{fix}}. Verify render parity in dev mode and a published view. Commit with message scope "blocks".',
    variables: [
      { key: 'blockType', label: 'Block type key', required: true, placeholder: 'stats' },
      { key: 'fix', label: 'Fix description', required: true, placeholder: 'Resolve brand sentinels for background color' },
    ],
  },
  {
    id: 'huashu-design',
    domain: 'cms-blocks',
    name: 'Huashu Design',
    description:
      'Vendored. Hi-fi single-file HTML for prototypes, decks, motion, infographics. Developer-facing only — output is inspiration, never copy-pasted into a typed block.',
    source: { kind: 'vendored-skill', path: '.agents/skills/huashu-design/SKILL.md' },
    icon: 'palette',
    estimatedRuntime: '10-20 min',
    appliesRules: ['huashu-not-pasteable'],
    trigger: 'on-demand',
    promptTemplate:
      'Use huashu-design to produce {{deliverable}} for "{{subject}}". Audience: {{audience}}. Design direction: {{direction}}. Output a self-contained HTML file. Remember: this is design exploration only — do not commit to the block registry.',
    variables: [
      { key: 'deliverable', label: 'Deliverable (prototype | slide-deck | motion-demo | variant-explorer | infographic)', required: true, placeholder: 'prototype' },
      { key: 'subject', label: 'Subject / brief', required: true, placeholder: 'Pricing page hero for an enrollment SaaS' },
      { key: 'audience', label: 'Audience', required: false, placeholder: 'Higher-ed enrollment VPs' },
      { key: 'direction', label: "Design direction (or 'advisor' to get 3 options)", required: false, placeholder: 'Kenya Hara east-minimal' },
    ],
  },

  // ─── visual-editor ─────────────────────────────────────────────────────
  {
    id: 'simplerdev-visual-editor',
    domain: 'visual-editor',
    name: 'SimplerDev Visual Editor',
    description:
      'Research/audit/debug/implement against the iframe page builder. Knows the postMessage protocol, the selection overlay, and the parent↔iframe invariants.',
    source: { kind: 'repo-skill', path: '.claude/skills/simplerdev-visual-editor/SKILL.md' },
    icon: 'design_services',
    estimatedRuntime: '10-20 min',
    trigger: 'on-demand',
    promptTemplate:
      'Use simplerdev-visual-editor in {{mode}} mode. Target: {{target}}. Symptom or goal: {{description}}. Read the surface map first — never touch the iframe and parent state without confirming the invariants.',
    variables: [
      { key: 'mode', label: 'Mode (research | audit | debug | implement)', required: true, placeholder: 'debug' },
      { key: 'target', label: 'Area (selection | drag | style-sidebar | layers-panel | postMessage | resize)', required: true, placeholder: 'selection' },
      { key: 'description', label: "What's broken or what to change", required: true, placeholder: 'Selection outline is wider than the rendered block on hero blocks' },
    ],
  },

  // ─── site-migration ────────────────────────────────────────────────────
  {
    id: 'site-migration',
    domain: 'site-migration',
    name: 'Site Migration',
    description:
      'Migrate an external website into a SimplerDevelopment tenant: scrape source, map sections to universal blocks, create client + site + pages, seed branding.',
    source: { kind: 'repo-skill', path: '.claude/skills/site-migration/SKILL.md' },
    icon: 'cloud_upload',
    estimatedRuntime: '30+ min',
    appliesRules: ['blocks-universal', 'tenancy-test', 'crosscap-email-pattern'],
    trigger: 'on-demand',
    promptTemplate:
      'Use site-migration to migrate "{{sourceUrl}}" into a SimplerDevelopment tenant. Client name: {{clientName}}. Subdomain: {{subdomain}}. Use the domain-derived email pattern ({{sitename}}@simplerdevelopment.com). Map sections to universal blocks; flag anything client-specific with the placeholder pattern.',
    variables: [
      { key: 'sourceUrl', label: 'Source URL to migrate', required: true, type: 'url', placeholder: 'https://www.example.com' },
      { key: 'clientName', label: 'Client display name', required: true, placeholder: 'Example Co.' },
      { key: 'subdomain', label: 'Target subdomain on simplerdevelopment.com', required: true, placeholder: 'exampleco' },
    ],
  },

  // ─── testing ───────────────────────────────────────────────────────────
  {
    id: 'e2e-writer',
    domain: 'testing',
    name: 'E2E Writer',
    description:
      'Generate new Playwright spec files with fixtures, idempotent cleanup, and tagging. Use for "write tests for feature X".',
    source: { kind: 'user-skill', path: '~/.claude/skills/e2e-writer/SKILL.md' },
    icon: 'edit_note',
    estimatedRuntime: '10-20 min',
    trigger: 'on-demand',
    promptTemplate:
      'Run /e2e-writer for the feature "{{feature}}". Cover: {{flows}}. Tag: {{tag}}. Use the fixtures in tests/e2e/setup/fixtures.ts and a createTest helper for cleanup.',
    variables: [
      { key: 'feature', label: 'Feature under test', required: true, placeholder: 'Service areas portal CRUD' },
      { key: 'flows', label: 'Flows to cover (comma-separated)', required: true, placeholder: 'create, list, edit, delete, unauthenticated' },
      { key: 'tag', label: 'Tag (critical | smoke | empty)', required: false, placeholder: 'critical' },
    ],
  },
  {
    id: 'e2e-runner',
    domain: 'testing',
    name: 'E2E Runner',
    description:
      'Run the existing Playwright suite (parallel-capable), analyze failures, fix flakes, report pass/fail.',
    source: { kind: 'user-skill', path: '~/.claude/skills/e2e-runner/SKILL.md' },
    icon: 'play_circle',
    estimatedRuntime: '10-20 min',
    trigger: 'on-demand',
    promptTemplate:
      'Run /e2e-runner in {{mode}} mode for tag "{{tag}}". If anything fails, debug and fix it. Re-run to confirm clean. Report pass/fail with a summary.',
    variables: [
      { key: 'mode', label: 'Mode (default | parallel)', required: false, placeholder: 'parallel' },
      { key: 'tag', label: 'Tag filter (critical | tenancy | smoke | all)', required: false, placeholder: 'critical' },
    ],
  },
  {
    id: 'qa',
    domain: 'testing',
    name: 'QA (Interactive / Exploratory / Video)',
    description:
      'Browser-driven visual QA with three modes: human-in-the-loop, autonomous exploration, or video walkthrough.',
    source: { kind: 'user-skill', path: '~/.claude/skills/qa/SKILL.md' },
    icon: 'visibility',
    estimatedRuntime: '10-20 min',
    trigger: 'on-demand',
    promptTemplate:
      'Run /qa in {{mode}} mode for the flow "{{flow}}". Starting URL: {{startUrl}}. {{modeSpecifics}}',
    variables: [
      { key: 'mode', label: 'Mode (interactive | exploratory | video)', required: true, placeholder: 'exploratory' },
      { key: 'flow', label: 'Flow under test', required: true, placeholder: 'New client onboarding' },
      { key: 'startUrl', label: 'Starting URL', required: true, type: 'url', placeholder: 'http://localhost:3000/portal' },
      { key: 'modeSpecifics', label: 'Extra context (e.g. test users, what to ignore)', required: false, placeholder: 'Use staging seed user dan+test@example.com' },
    ],
  },
  {
    id: 'e2e-visual-tester',
    domain: 'testing',
    name: 'E2E Visual Tester (subagent)',
    description:
      'Focused Playwright agent that pairs with simplerdev-visual-editor to verify editor flows render correctly across viewports.',
    source: { kind: 'subagent', name: 'e2e-visual-tester' },
    icon: 'devices',
    estimatedRuntime: '10-20 min',
    trigger: 'on-demand',
    promptTemplate:
      'Use e2e-visual-tester to verify the visual editor flow "{{flow}}" across viewports: {{viewports}}. Capture screenshots and report any regressions.',
    variables: [
      { key: 'flow', label: 'Editor flow to test', required: true, placeholder: 'Drag a hero block then resize via overlay handles' },
      { key: 'viewports', label: 'Viewports (comma-separated)', required: false, placeholder: 'desktop, mobile' },
    ],
  },

  // ─── mcp-server ────────────────────────────────────────────────────────
  {
    id: 'simplerdev-mcp-tool',
    domain: 'mcp-server',
    name: 'SimplerDev MCP Tool',
    description:
      'Register a new MCP tool in lib/mcp/server.ts (or an adapter file) with handler + Zod schema + scope guard, slim-by-default.',
    source: { kind: 'repo-skill', path: '.claude/skills/simplerdev-mcp-tool/SKILL.md' },
    icon: 'plug_connect',
    estimatedRuntime: '5-10 min',
    appliesRules: ['mcp-slim-payloads'],
    trigger: 'on-demand',
    promptTemplate:
      'Use simplerdev-mcp-tool to register a new MCP tool named "{{toolName}}" for domain "{{domain}}". Inputs: {{inputs}}. Required scope: {{scope}}. Description: {{description}}. Use slim projections by default.',
    variables: [
      { key: 'toolName', label: 'Tool name (snake_case, domain-prefixed)', required: true, placeholder: 'crm_deals_archive' },
      { key: 'domain', label: 'Domain (crm | brain | posts | tickets | etc.)', required: true, placeholder: 'crm' },
      { key: 'inputs', label: 'Input schema (Zod-shape pseudocode)', required: true, placeholder: 'dealId: number, reason: string optional' },
      { key: 'scope', label: 'Required scope', required: true, placeholder: 'crm:write' },
      { key: 'description', label: 'One-sentence description', required: true, placeholder: 'Archive a CRM deal without deleting it' },
    ],
  },
  {
    id: 'simplerdev-mcp-token-budget',
    domain: 'mcp-server',
    name: 'SimplerDev MCP Token Budget Audit',
    description:
      'Audit MCP tool payloads — enforce slim projections, opt-in heavy fields, compact write-echoes. Run after any tool that touches a body/HTML/blocks column.',
    source: { kind: 'repo-skill', path: '.claude/skills/simplerdev-mcp-token-budget/SKILL.md' },
    icon: 'compress',
    estimatedRuntime: '10-20 min',
    appliesRules: ['mcp-slim-payloads'],
    trigger: 'on-demand',
    promptTemplate:
      'Use simplerdev-mcp-token-budget to audit the MCP tool "{{toolName}}" (or all tools in domain "{{domain}}"). Enforce slim-by-default projections, gate heavy fields behind an include flag, and trim write-echoes. Report tokens saved.',
    variables: [
      { key: 'toolName', label: 'Specific tool (or leave empty for full-domain audit)', required: false, placeholder: 'posts_list' },
      { key: 'domain', label: 'Domain to audit if no tool given', required: false, placeholder: 'posts' },
    ],
  },
  {
    id: 'mcp-server-builder',
    domain: 'mcp-server',
    name: 'MCP Server Builder (subagent)',
    description:
      'Generalized MCP adapter authoring for new feature domains — produces an lib/<feature>/mcp-*.ts adapter that the main server file imports.',
    source: { kind: 'subagent', name: 'mcp-server-builder' },
    icon: 'integration_instructions',
    estimatedRuntime: '20-30 min',
    appliesRules: ['mcp-slim-payloads'],
    trigger: 'on-demand',
    promptTemplate:
      'Use mcp-server-builder to scaffold an MCP adapter for feature domain "{{domain}}". Tools to expose: {{tools}}. Output goes to lib/{{domain}}/mcp-{{domain}}.ts. Wire into lib/mcp/server.ts.',
    variables: [
      { key: 'domain', label: 'Feature domain', required: true, placeholder: 'leases' },
      { key: 'tools', label: 'Tool list (comma-separated names)', required: true, placeholder: 'leases_list, leases_get, leases_create, leases_update' },
    ],
  },

  // ─── content-research ──────────────────────────────────────────────────
  {
    id: 'research-competitor',
    domain: 'content-research',
    name: 'Research Competitor',
    description:
      'Combine vault material with WebSearch to produce a competitor synthesis brief, written into the postcaptain-kb discoveries/ directory.',
    source: { kind: 'user-skill', path: '~/.claude/skills/research-competitor/SKILL.md' },
    icon: 'search',
    estimatedRuntime: '10-20 min',
    trigger: 'on-demand',
    promptTemplate:
      'Use research-competitor on "{{competitor}}". Focus: {{focus}}. Write the brief to discoveries/YYYY-MM-DD-competitor-<slug>.md in the postcaptain-kb vault.',
    variables: [
      { key: 'competitor', label: 'Competitor name or slug', required: true, placeholder: 'waybettermarketing' },
      { key: 'focus', label: 'Optional angle', required: false, placeholder: 'How they price their AI features' },
    ],
  },
  {
    id: 'draft-blog-post',
    domain: 'content-research',
    name: 'Draft Blog Post',
    description:
      'Mine the postcaptain-kb vault + external sources, draft a single blog post into drafts/YYYY-MM-DD-<slug>.md. Not publish-ready — meant for review and edit.',
    source: { kind: 'user-skill', path: '~/.claude/skills/draft-blog-post/SKILL.md' },
    icon: 'article',
    estimatedRuntime: '20-30 min',
    trigger: 'on-demand',
    promptTemplate:
      'Use draft-blog-post to write a Post Captain draft on "{{topic}}". Angle: {{angle}}. Length: {{length}}. Seed note: {{seedNote}}.',
    variables: [
      { key: 'topic', label: 'Topic / headline idea', required: true, placeholder: 'Why most enrollment-marketing dashboards lie' },
      { key: 'angle', label: 'Audience / format / opinion', required: false, placeholder: 'Deep dive for enrollment VPs' },
      { key: 'length', label: 'Length', required: false, placeholder: '~1200 words' },
      { key: 'seedNote', label: 'Optional seed note path in vault', required: false, placeholder: 'discoveries/2026-04-10-higher-ed-enrollment-marketing-trends.md' },
    ],
  },
  {
    id: 'video-ingest',
    domain: 'content-research',
    name: 'Video Ingest',
    description:
      'Transcribe a YouTube URL or local video file, sample frames, write transcript.txt + frames/ + summary.md under ~/.claude/video-ingest/.',
    source: { kind: 'user-skill', path: '~/.claude/skills/video-ingest/SKILL.md' },
    icon: 'movie',
    estimatedRuntime: '10-20 min',
    trigger: 'on-demand',
    promptTemplate:
      'Use video-ingest on "{{source}}". Question to bias the summary toward: {{question}}. Frame count: {{frameCount}}.',
    variables: [
      { key: 'source', label: 'YouTube URL or absolute local file path', required: true, placeholder: 'https://youtu.be/abc123' },
      { key: 'question', label: 'What you want from it', required: false, placeholder: "What's the framework for Domains→Tasks→Skills→Automations?" },
      { key: 'frameCount', label: 'Number of frames', required: false, placeholder: '12' },
    ],
  },
  {
    id: 'obsidian-note-taker',
    domain: 'content-research',
    name: 'Obsidian Note Taker (subagent)',
    description:
      "Writes a structured note (daily log, ADR, spec, session summary) into the vault using the project's note conventions.",
    source: { kind: 'subagent', name: 'obsidian-note-taker' },
    icon: 'note_add',
    estimatedRuntime: '1-3 min',
    trigger: 'on-demand',
    promptTemplate:
      "Use obsidian-note-taker to capture a {{noteType}} note. Subject: {{subject}}. Details: {{details}}. Use the project's note conventions.",
    variables: [
      { key: 'noteType', label: 'Note type (daily-log | ADR | spec | research | session-summary)', required: true, placeholder: 'ADR' },
      { key: 'subject', label: 'Subject', required: true, placeholder: 'Switch automations queue from in-process to cron-claim CAS' },
      { key: 'details', label: 'Body / context', required: true, placeholder: 'We decided to use SELECT FOR UPDATE SKIP LOCKED...', type: 'textarea' },
    ],
  },

  // ─── qa-visual ─────────────────────────────────────────────────────────
  {
    id: 'visual-compare',
    domain: 'qa-visual',
    name: 'Visual Compare',
    description:
      'Capture two versions of the same UI side-by-side and report a per-section pixel + content match verdict. Used to verify ports and redesigns.',
    source: { kind: 'user-skill', path: '~/.claude/skills/visual-compare/SKILL.md' },
    icon: 'compare',
    estimatedRuntime: '5-10 min',
    trigger: 'on-demand',
    promptTemplate:
      'Use visual-compare to side-by-side compare "{{leftLabel}}" ({{leftSource}}) against "{{rightLabel}}" ({{rightSource}}). Viewport: {{viewport}}. Report per-section verdicts.',
    variables: [
      { key: 'leftLabel', label: 'Left label', required: true, placeholder: 'Original HTML deck' },
      { key: 'leftSource', label: 'Left source (URL or path)', required: true, placeholder: '/Users/dan/desks/v3.html' },
      { key: 'rightLabel', label: 'Right label', required: true, placeholder: 'Portal-rendered deck' },
      { key: 'rightSource', label: 'Right source', required: true, placeholder: 'https://staging.simplerdevelopment.com/p/abc' },
      { key: 'viewport', label: 'Viewport', required: false, placeholder: '1920x1080' },
    ],
  },

  // ─── kb-vault ──────────────────────────────────────────────────────────
  {
    id: 'connect-kb',
    domain: 'kb-vault',
    name: 'Connect KB',
    description:
      'One-time / repair wiring of the Obsidian Local REST API MCP server so other vault skills can read and write notes.',
    source: { kind: 'user-skill', path: '~/.claude/skills/connect-kb/SKILL.md' },
    icon: 'cable',
    estimatedRuntime: '1-3 min',
    trigger: 'on-demand',
    promptTemplate:
      "Use connect-kb to wire up the postcaptain-kb Obsidian vault via the Local REST API MCP server. If it's already connected, verify and report; otherwise walk me through the API key step.",
    variables: [],
  },
  {
    id: 'sync-kb',
    domain: 'kb-vault',
    name: 'Sync KB',
    description:
      "Stage, commit, and push pending changes in the postcaptain-kb vault with conventional-commit messages matching the repo's style.",
    source: { kind: 'user-skill', path: '~/.claude/skills/sync-kb/SKILL.md' },
    icon: 'cloud_sync',
    estimatedRuntime: '1-3 min',
    trigger: 'on-demand',
    promptTemplate:
      "Use sync-kb to commit and push pending changes in the postcaptain-kb vault. Infer commit type and scope from the changed paths. Don't amend, don't force-push.",
    variables: [],
  },

  // ─── automations-cron ──────────────────────────────────────────────────
  {
    id: 'cron-expire-mcp-pendings',
    domain: 'automations-cron',
    name: 'Expire MCP Pendings',
    description: 'Daily 03:17 UTC. Expire stale MCP pending changes that the user never confirmed.',
    source: { kind: 'cron-route', path: 'app/api/cron/expire-mcp-pendings/route.ts', schedule: '17 3 * * *' },
    icon: 'schedule',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '17 3 * * *',
    manualRunPath: '/api/cron/expire-mcp-pendings',
  },
  {
    id: 'cron-renew-gmail-watches',
    domain: 'automations-cron',
    name: 'Renew Gmail Watches',
    description: 'Daily 03:47 UTC. Re-watch Gmail mailboxes whose users.watch() is within 48h of expiry; bootstrap any new gmail-scoped connections.',
    source: { kind: 'cron-route', path: 'app/api/cron/renew-gmail-watches/route.ts', schedule: '47 3 * * *' },
    icon: 'mail',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '47 3 * * *',
    manualRunPath: '/api/cron/renew-gmail-watches',
  },
  {
    id: 'cron-renew-drive-watches',
    domain: 'automations-cron',
    name: 'Renew Drive Watches',
    description: 'Daily 04:13 UTC. Re-subscribe Drive HTTP push channels nearing their 1-day expiry.',
    source: { kind: 'cron-route', path: 'app/api/cron/renew-drive-watches/route.ts', schedule: '13 4 * * *' },
    icon: 'folder_shared',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '13 4 * * *',
    manualRunPath: '/api/cron/renew-drive-watches',
  },
  {
    id: 'cron-resend-usage-sync',
    domain: 'automations-cron',
    name: 'Resend Usage Sync',
    description: 'Daily 04:15 UTC. Roll up per-client email-send counts for the current YYYY-MM and upsert into usage_meter_events.',
    source: { kind: 'cron-route', path: 'app/api/cron/resend-usage-sync/route.ts', schedule: '15 4 * * *' },
    icon: 'sync',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '15 4 * * *',
    manualRunPath: '/api/cron/resend-usage-sync',
  },
  {
    id: 'cron-usage-rollup',
    domain: 'automations-cron',
    name: 'Stripe Usage Rollup',
    description: 'Daily 04:45 UTC. Push current-period metered usage to Stripe per client; idempotent on (client, period, resource).',
    source: { kind: 'cron-route', path: 'app/api/cron/usage-rollup/route.ts', schedule: '45 4 * * *' },
    icon: 'payments',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '45 4 * * *',
    manualRunPath: '/api/cron/usage-rollup',
  },
  {
    id: 'cron-drive-sync',
    domain: 'automations-cron',
    name: 'Drive Sync',
    description: "Every 10 minutes. Incremental Drive change sync; ingests Google Docs in each user's Meet Recordings folder as brain_meetings.",
    source: { kind: 'cron-route', path: 'app/api/cron/drive-sync/route.ts', schedule: '*/10 * * * *' },
    icon: 'cloud_download',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '*/10 * * * *',
    manualRunPath: '/api/cron/drive-sync',
  },
  {
    id: 'cron-process-embeddings',
    domain: 'automations-cron',
    name: 'Process Embeddings',
    description: 'Every minute. Drain brain_embedding_jobs queue with FOR UPDATE SKIP LOCKED — safe under concurrency.',
    source: { kind: 'cron-route', path: 'app/api/cron/process-embeddings/route.ts', schedule: '* * * * *' },
    icon: 'bolt',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '* * * * *',
    manualRunPath: '/api/cron/process-embeddings',
  },
  {
    id: 'cron-brain-daily-notes',
    domain: 'automations-cron',
    name: 'Brain Daily Notes',
    description: "Daily 06:05 UTC. Materialize today's daily note for every tenant with a trigger='daily' template. Idempotent on (clientId, YYYY-MM-DD).",
    source: { kind: 'cron-route', path: 'app/api/cron/brain-daily-notes/route.ts', schedule: '5 6 * * *' },
    icon: 'edit_calendar',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '5 6 * * *',
    manualRunPath: '/api/cron/brain-daily-notes',
  },
  {
    id: 'cron-brain-empty-old-trash',
    domain: 'automations-cron',
    name: 'Brain Empty Old Trash',
    description: "Daily 07:15 UTC. Auto-purge brain notes that have been trashed for >90 days; per-tenant fan-out so one failure doesn't abort the sweep.",
    source: { kind: 'cron-route', path: 'app/api/cron/brain-empty-old-trash/route.ts', schedule: '15 7 * * *' },
    icon: 'delete_sweep',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '15 7 * * *',
    manualRunPath: '/api/cron/brain-empty-old-trash',
  },
  {
    id: 'cron-brain-12',
    domain: 'automations-cron',
    name: 'BRAIN-12 One-Shot Cleanup',
    description: 'Daily 07:30 UTC, but fires meaningful work on only two dates (2026-05-26 reminder, 2026-06-06 bulk soft-delete) for client 100.',
    source: { kind: 'cron-route', path: 'app/api/cron/brain-12/route.ts', schedule: '30 7 * * *' },
    icon: 'event_repeat',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '30 7 * * *',
    manualRunPath: '/api/cron/brain-12',
  },
  {
    id: 'cron-failing-automations-notify',
    domain: 'automations-cron',
    name: 'Failing Automations Notify',
    description: 'Daily 12:00 UTC. Scan automation rules whose last 5 runs are all failed; broadcast one in-app notification per match to the owning tenant.',
    source: { kind: 'cron-route', path: 'app/api/cron/failing-automations-notify/route.ts', schedule: '0 12 * * *' },
    icon: 'notifications_active',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '0 12 * * *',
    manualRunPath: '/api/cron/failing-automations-notify',
  },
  {
    id: 'cron-surveys-zero-responses',
    domain: 'automations-cron',
    name: 'Surveys Zero Responses',
    description: 'Weekly Mon 10:30 UTC. Notify survey owners whose active surveys are 14-60 days old with no responses.',
    source: { kind: 'cron-route', path: 'app/api/cron/surveys-zero-responses/route.ts', schedule: '30 10 * * 1' },
    icon: 'poll',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '30 10 * * 1',
    manualRunPath: '/api/cron/surveys-zero-responses',
  },
  {
    id: 'cron-stale-crm-deals',
    domain: 'automations-cron',
    name: 'Stale CRM Deals',
    description: 'Weekly Mon 11:00 UTC. Notify deal owners of open deals with no activity in 30+ days; 30-day dedupe to avoid flapping.',
    source: { kind: 'cron-route', path: 'app/api/cron/stale-crm-deals/route.ts', schedule: '0 11 * * 1' },
    icon: 'pending_actions',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '0 11 * * 1',
    manualRunPath: '/api/cron/stale-crm-deals',
  },
  {
    id: 'cron-stuck-booking-holds',
    domain: 'automations-cron',
    name: 'Stuck Booking Holds',
    description: "Every 30 minutes. Detect bookings with paymentStatus='pending' for 24+ hours and notify the page owner (preview mode — no auto-cancel yet).",
    source: { kind: 'cron-route', path: 'app/api/cron/stuck-booking-holds/route.ts', schedule: '*/30 * * * *' },
    icon: 'hourglass_top',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '*/30 * * * *',
    manualRunPath: '/api/cron/stuck-booking-holds',
  },
  {
    id: 'cron-renew-microsoft-subscriptions',
    domain: 'automations-cron',
    name: 'Renew Microsoft Subscriptions',
    description: 'Every 25 minutes. Renew Teams transcript subscriptions (50-min lifetime); bootstrap new connections without one.',
    source: { kind: 'cron-route', path: 'app/api/cron/renew-microsoft-subscriptions/route.ts', schedule: '*/25 * * * *' },
    icon: 'autorenew',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '*/25 * * * *',
    manualRunPath: '/api/cron/renew-microsoft-subscriptions',
  },
  {
    id: 'cron-pm-recurrences',
    domain: 'automations-cron',
    name: 'PM Recurrences',
    description: 'Every 5 minutes. Materialize cards from due card_recurrences rows.',
    source: { kind: 'cron-route', path: 'app/api/cron/pm-recurrences/route.ts', schedule: '*/5 * * * *' },
    icon: 'repeat',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '*/5 * * * *',
    manualRunPath: '/api/cron/pm-recurrences',
  },
  {
    id: 'cron-pm-column-snapshots',
    domain: 'automations-cron',
    name: 'PM Column Snapshots',
    description: 'Daily 23:55 UTC. Snapshot kanban column counts for the cumulative flow diagram; idempotent on (projectId, columnId, snapshotDate).',
    source: { kind: 'cron-route', path: 'app/api/cron/pm-column-snapshots/route.ts', schedule: '55 23 * * *' },
    icon: 'view_column',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '55 23 * * *',
    manualRunPath: '/api/cron/pm-column-snapshots',
  },
  {
    id: 'cron-process-survey-email-followups',
    domain: 'automations-cron',
    name: 'Survey Email Follow-ups',
    description: 'Every 15 minutes. DIST-01/02 worker — dispatch follow-up emails for matching survey responses, capped at 100/tick, unique-indexed against double-send.',
    source: { kind: 'cron-route', path: 'app/api/cron/process-survey-email-followups/route.ts', schedule: '*/15 * * * *' },
    icon: 'forward_to_inbox',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '*/15 * * * *',
    manualRunPath: '/api/cron/process-survey-email-followups',
  },
  {
    id: 'cron-process-scheduled-automations',
    domain: 'automations-cron',
    name: 'Process Scheduled Automations',
    description: 'Every minute. Fire all automation rules whose next_run_at is past; CAS-claim to guarantee single firing under concurrent workers.',
    source: { kind: 'cron-route', path: 'app/api/cron/process-scheduled-automations/route.ts', schedule: '* * * * *' },
    icon: 'bolt',
    estimatedRuntime: '1-3 min',
    appliesRules: ['cron-auth-pattern'],
    trigger: 'scheduled',
    cronExpression: '* * * * *',
    manualRunPath: '/api/cron/process-scheduled-automations',
  },
];

export const SKILLS_BY_ID: Readonly<Record<string, AgenticOsSkill>> =
  Object.fromEntries(SKILLS.map(s => [s.id, s]));

export function skillsByDomain(): Readonly<Record<AgenticOsDomain, readonly AgenticOsSkill[]>> {
  const out = {} as Record<AgenticOsDomain, AgenticOsSkill[]>;
  for (const s of SKILLS) {
    (out[s.domain] ||= []).push(s);
  }
  return out;
}
