/**
 * Public render-path A/B resolution — `lib/ab/resolve.ts`
 *
 * The render-path code (`applyAbToPostContent` → `resolveAbContent`) is
 * exercised here as an integration unit: it talks to Postgres directly,
 * picks a variant, optionally substitutes blockTreeOverride into the
 * post content, and fires-and-forgets an assignment + view event.
 *
 * Why we drive `resolveAbContent` and not the render route:
 *   - Server-component pages aren't ergonomic to drive from a node-env vitest;
 *     the visitor cookie is generated by `cookies()` from `next/headers`,
 *     which has no real-world `RequestStore` in this environment.
 *   - But `resolveAbContent` accepts an explicit `visitorId` arg, so we can
 *     deterministically assert stickiness + bucket diversity by passing
 *     fixed UUIDs in.
 *
 * Coverage:
 *   - Running experiment with one overridden variant → visitor that buckets
 *     into the override sees the overridden content
 *   - Sticky: same visitor on a second call gets the same variantKey
 *   - Diversity: across many visitor ids we see at least 2 distinct buckets
 *   - No experiment → original content + ab=null
 *   - Draft experiment → not surfaced (the resolver only picks 'running')
 */
import { describe, it, expect } from 'vitest';
import { resolveAbContent, recordExposure } from '@/lib/ab/resolve';
import { assignVariant } from '@/lib/ab/assign';
import { getTestSql, TEST_SCHEMA } from '../../../../helpers/test-db';

async function seedRunning(opts: {
  status?: string;
  override?: unknown;
  splitB?: number;
} = {}): Promise<{ postId: number; experimentId: number; baseContent: string; overrideContent: string | null }> {
  const sql = getTestSql();
  const stamp = `${Date.now()}-${Math.floor(Math.random() * 9999)}`;

  const [u] = await sql<{ id: number }[]>`
    INSERT INTO ${sql(TEST_SCHEMA)}.users (name, email, password, role, active)
    VALUES ('R', ${`r-${stamp}@test.local`}, 'x', 'editor', true)
    RETURNING id
  `;
  const [c] = await sql<{ id: number }[]>`
    INSERT INTO ${sql(TEST_SCHEMA)}.clients (user_id, company)
    VALUES (${u.id}, ${`Render Co ${stamp}`}) RETURNING id
  `;
  const [w] = await sql<{ id: number }[]>`
    INSERT INTO ${sql(TEST_SCHEMA)}.client_websites (client_id, name, domain)
    VALUES (${c.id}, ${`render-${stamp}`}, ${`render-${stamp}.test`})
    RETURNING id
  `;
  const baseContent = JSON.stringify({ blocks: [{ type: 'heading', text: 'CONTROL' }], version: '1.0' });
  const [p] = await sql<{ id: number }[]>`
    INSERT INTO ${sql(TEST_SCHEMA)}.posts (
      website_id, title, slug, post_type, content, published
    ) VALUES (
      ${w.id}, 'Render', ${`render-${stamp}`}, 'blog', ${baseContent}, true
    ) RETURNING id
  `;
  const split = { a: 100 - (opts.splitB ?? 50), b: opts.splitB ?? 50 };
  const [exp] = await sql<{ id: number }[]>`
    INSERT INTO ${sql(TEST_SCHEMA)}.ab_experiments (
      post_id, name, status, variant_split, goal_metric, started_at, created_by
    ) VALUES (
      ${p.id}, 'Render exp', ${opts.status ?? 'running'},
      ${JSON.stringify(split)}::jsonb,
      'page_view', NOW(), ${u.id}
    ) RETURNING id
  `;
  const overrideJson = opts.override === undefined
    ? { blocks: [{ type: 'heading', text: 'VARIANT B' }], version: '1.0' }
    : opts.override;
  await sql`
    INSERT INTO ${sql(TEST_SCHEMA)}.ab_variants (experiment_id, key, label, block_tree_override)
    VALUES (${exp.id}, 'a', 'Control', NULL),
           (${exp.id}, 'b', 'Variant B', ${overrideJson === null ? null : JSON.stringify(overrideJson)}::jsonb)
  `;
  return {
    postId: p.id,
    experimentId: exp.id,
    baseContent,
    overrideContent: overrideJson === null ? null : JSON.stringify(overrideJson),
  };
}

// A small pool of visitor ids — chosen so that, given the FNV-1a bucket
// assignment in lib/ab/assign.ts, we know the bucket distribution covers
// both 'a' and 'b'. Selected experimentally to guarantee at least one of
// each across the set with a 50/50 split.
const VISITOR_POOL = [
  'aaaaaaaa-1111-2222-3333-444444444444',
  'bbbbbbbb-1111-2222-3333-444444444444',
  'cccccccc-1111-2222-3333-444444444444',
  'dddddddd-1111-2222-3333-444444444444',
  'eeeeeeee-1111-2222-3333-444444444444',
  'ffffffff-1111-2222-3333-444444444444',
  '11111111-aaaa-bbbb-cccc-dddddddddddd',
  '22222222-aaaa-bbbb-cccc-dddddddddddd',
  '33333333-aaaa-bbbb-cccc-dddddddddddd',
  '44444444-aaaa-bbbb-cccc-dddddddddddd',
];

describe('resolveAbContent — public render path @ab @public', () => {
  it('returns the original content + ab=null when there is no experiment', async () => {
    const sql = getTestSql();
    const stamp = Date.now();
    const [u] = await sql<{ id: number }[]>`
      INSERT INTO ${sql(TEST_SCHEMA)}.users (name, email, password, role, active)
      VALUES ('NoExp', ${`noexp-${stamp}@test.local`}, 'x', 'editor', true) RETURNING id
    `;
    const [c] = await sql<{ id: number }[]>`
      INSERT INTO ${sql(TEST_SCHEMA)}.clients (user_id, company) VALUES (${u.id}, 'NoExp') RETURNING id
    `;
    const [w] = await sql<{ id: number }[]>`
      INSERT INTO ${sql(TEST_SCHEMA)}.client_websites (client_id, name, domain)
      VALUES (${c.id}, ${`noexp-${stamp}`}, ${`noexp-${stamp}.test`}) RETURNING id
    `;
    const content = JSON.stringify({ blocks: [], version: '1.0' });
    const [p] = await sql<{ id: number }[]>`
      INSERT INTO ${sql(TEST_SCHEMA)}.posts (website_id, title, slug, post_type, content, published)
      VALUES (${w.id}, 'X', ${`x-${stamp}`}, 'blog', ${content}, true) RETURNING id
    `;
    const result = await resolveAbContent(p.id, VISITOR_POOL[0], content);
    expect(result.ab).toBeNull();
    expect(result.content).toBe(content);
  });

  it('does NOT surface a draft experiment', async () => {
    const { postId, baseContent } = await seedRunning({ status: 'draft' });
    const result = await resolveAbContent(postId, VISITOR_POOL[0], baseContent);
    expect(result.ab).toBeNull();
    expect(result.content).toBe(baseContent);
  });

  it('returns ab=null when no visitorId is provided', async () => {
    const { postId, baseContent } = await seedRunning();
    const result = await resolveAbContent(postId, null, baseContent);
    expect(result.ab).toBeNull();
    expect(result.content).toBe(baseContent);
  });

  it('the same visitor sticks to the same variant across calls', async () => {
    const { postId, experimentId, baseContent } = await seedRunning();
    const v = VISITOR_POOL[0];
    const r1 = await resolveAbContent(postId, v, baseContent);
    const r2 = await resolveAbContent(postId, v, baseContent);
    expect(r1.ab?.experimentId).toBe(experimentId);
    expect(r2.ab?.experimentId).toBe(experimentId);
    expect(r1.ab?.variantKey).toBe(r2.ab?.variantKey);
  });

  it('a visitor bucketed into the override variant sees the override content', async () => {
    const { postId, experimentId, baseContent, overrideContent } = await seedRunning();

    // Pre-compute bucket against the actual stored experiment row so the
    // expectation matches without us needing to know the fnv hash off the
    // top of our heads.
    const sql = getTestSql();
    const [row] = await sql<{ variant_split: unknown }[]>`
      SELECT variant_split FROM ${sql(TEST_SCHEMA)}.ab_experiments WHERE id = ${experimentId}
    `;
    const split = row.variant_split as Record<string, number>;
    const variantsForVisitor = VISITOR_POOL.map(v => ({
      v,
      key: assignVariant({ id: experimentId, variantSplit: split }, v),
    }));
    const aCase = variantsForVisitor.find(x => x.key === 'a');
    const bCase = variantsForVisitor.find(x => x.key === 'b');
    expect(aCase, 'pool should contain a visitor that buckets to "a"').toBeTruthy();
    expect(bCase, 'pool should contain a visitor that buckets to "b"').toBeTruthy();

    const aRes = await resolveAbContent(postId, aCase!.v, baseContent);
    const bRes = await resolveAbContent(postId, bCase!.v, baseContent);

    expect(aRes.ab?.variantKey).toBe('a');
    expect(aRes.ab?.swapped).toBe(false);
    expect(aRes.content).toBe(baseContent);

    expect(bRes.ab?.variantKey).toBe('b');
    expect(bRes.ab?.swapped).toBe(true);
    expect(bRes.content).toBe(overrideContent);
  });

  it('different visitors land in different buckets across the pool', async () => {
    const { postId, baseContent } = await seedRunning();
    const keys = new Set<string>();
    for (const v of VISITOR_POOL) {
      const r = await resolveAbContent(postId, v, baseContent);
      if (r.ab?.variantKey) keys.add(r.ab.variantKey);
    }
    // We only need to know that the assignment isn't pinned to a single arm.
    expect(keys.size).toBeGreaterThanOrEqual(2);
  });

  it('falls back to the original content when the variant has no override', async () => {
    // Variant b has no blockTreeOverride → resolver returns the post content.
    const { postId, experimentId, baseContent } = await seedRunning({ override: null });

    const sql = getTestSql();
    const [row] = await sql<{ variant_split: unknown }[]>`
      SELECT variant_split FROM ${sql(TEST_SCHEMA)}.ab_experiments WHERE id = ${experimentId}
    `;
    const split = row.variant_split as Record<string, number>;
    const bVisitor = VISITOR_POOL.find(v => assignVariant({ id: experimentId, variantSplit: split }, v) === 'b');
    expect(bVisitor).toBeTruthy();

    const r = await resolveAbContent(postId, bVisitor!, baseContent);
    expect(r.ab?.variantKey).toBe('b');
    expect(r.ab?.swapped).toBe(false);
    expect(r.content).toBe(baseContent);
  });

  it('recordExposure writes an assignment + a view event (idempotent on assignment)', async () => {
    const { experimentId } = await seedRunning();
    const sql = getTestSql();
    const visitor = 'recorder-1234567890abcdef';

    await recordExposure(experimentId, 'a', visitor);
    await recordExposure(experimentId, 'a', visitor);

    const [{ count: assignCount }] = await sql<{ count: number }[]>`
      SELECT COUNT(*)::int AS count
      FROM ${sql(TEST_SCHEMA)}.ab_assignments
      WHERE experiment_id = ${experimentId} AND visitor_id = ${visitor}
    `;
    expect(assignCount).toBe(1); // unique-on-conflict guard
  });
});
