/**
 * Manifest loading + command lookup + arg coercion.
 *
 * `manifest.json` is generated by `scripts/generate-cli-manifest.ts`
 * (introspects the MCP server's Zod schemas at build time) and committed to
 * `packages/cli/manifest.json`. It's the single source of truth for the
 * generated command surface — the CLI itself has one generic dispatch path.
 */

import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { CliError } from './client.js';

export type ArgType = 'string' | 'number' | 'boolean' | 'json';

export interface ManifestArgSpec {
  name: string;
  type: ArgType;
  required?: boolean;
  enum?: string[];
  desc?: string;
}

export interface ManifestToolSpec {
  name: string;
  cmd: string;
  domain: string;
  desc?: string;
  destructive?: boolean;
  scope?: string;
  args?: ManifestArgSpec[];
}

export interface ManifestDomainSpec {
  name: string;
  tools: number;
}

export interface Manifest {
  manifestVersion: number;
  toolCount: number;
  domains: ManifestDomainSpec[];
  tools: ManifestToolSpec[];
  builtins?: string[];
}

/**
 * Path to the shipped manifest.json, resolved relative to this module so it
 * works both from `dist/index.js` (bundled, one dir below `packages/cli/`)
 * and from `bun packages/cli/src/index.ts` (also one dir below).
 */
export function resolveManifestPath(): string {
  return fileURLToPath(new URL('../manifest.json', import.meta.url));
}

export function loadManifestFromPath(path: string): Manifest {
  if (!existsSync(path)) {
    throw new CliError(
      `Manifest not found at ${path}. Run \`bun run cli:manifest\` to generate it.`,
      2,
      'manifest_missing',
    );
  }
  let raw: string;
  try {
    raw = readFileSync(path, 'utf-8');
  } catch (err) {
    throw new CliError(
      `Could not read manifest at ${path}: ${err instanceof Error ? err.message : String(err)}`,
      2,
      'manifest_missing',
    );
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new CliError(
      `Manifest at ${path} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
      2,
      'manifest_missing',
    );
  }
  if (
    !parsed ||
    typeof parsed !== 'object' ||
    !Array.isArray((parsed as Manifest).tools) ||
    !Array.isArray((parsed as Manifest).domains)
  ) {
    throw new CliError(`Manifest at ${path} is malformed (missing tools[]/domains[]).`, 2, 'manifest_missing');
  }
  return parsed as Manifest;
}

export function loadManifest(): Manifest {
  return loadManifestFromPath(resolveManifestPath());
}

/** Look up a tool by its dispatch command, e.g. `["posts", "list"]` -> posts_list. */
export function findByCmd(manifest: Manifest, cmdParts: string[]): ManifestToolSpec | undefined {
  const cmd = cmdParts.join(' ');
  return manifest.tools.find((t) => t.cmd === cmd);
}

/** Look up a tool by its raw MCP tool name, e.g. `posts_list` — used by `simpler call`. */
export function findByName(manifest: Manifest, name: string): ManifestToolSpec | undefined {
  return manifest.tools.find((t) => t.name === name);
}

export function domainNames(manifest: Manifest): string[] {
  return manifest.domains.map((d) => d.name);
}

/** All commands belonging to one domain, e.g. `simpler manifest posts`. */
export function domainCommands(manifest: Manifest, domain: string): ManifestToolSpec[] {
  return manifest.tools.filter((t) => t.domain === domain);
}

/** `--flag-name` -> schema arg name, e.g. `require-cms-approval` -> `requireCmsApproval`. */
export function toKebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase();
}

export interface CoercionInput {
  /** Flags as parsed from argv, keyed by kebab-case flag name (no leading --). */
  flags: Record<string, string | boolean>;
  /** Parsed --file payload (lowest precedence). */
  filePayload?: Record<string, unknown>;
  /** Parsed --args JSON payload (middle precedence). */
  argsJson?: Record<string, unknown>;
}

export interface CoercionResult {
  args: Record<string, unknown>;
  /** Non-empty means: print a usage error and exit(2) — don't call the tool. */
  errors: string[];
}

function coerceScalar(raw: string | boolean, type: ArgType): { value: unknown } | { error: string } {
  switch (type) {
    case 'string':
      return { value: typeof raw === 'boolean' ? String(raw) : raw };
    case 'number': {
      const n = Number(raw);
      if (Number.isNaN(n)) return { error: `expected a number` };
      return { value: n };
    }
    case 'boolean': {
      if (typeof raw === 'boolean') return { value: raw };
      if (raw === 'true') return { value: true };
      if (raw === 'false') return { value: false };
      return { error: `expected true or false` };
    }
    case 'json': {
      const s = typeof raw === 'boolean' ? String(raw) : raw;
      try {
        return { value: JSON.parse(s) };
      } catch {
        return { error: `expected a JSON string` };
      }
    }
    default:
      return { error: `unknown arg type` };
  }
}

/**
 * Merge --file payload < --args JSON < individual --flags (flags win), coerce
 * each flag to its schema type, validate enums + required args, and flag
 * unknown flags. Returns `errors` non-empty when the caller should print a
 * usage error and exit(2) instead of dispatching the call.
 */
export function coerceArgs(toolSpec: ManifestToolSpec, input: CoercionInput): CoercionResult {
  const specs = toolSpec.args ?? [];
  const specByFlag = new Map(specs.map((spec) => [toKebab(spec.name), spec]));

  const merged: Record<string, unknown> = {
    ...(input.filePayload ?? {}),
    ...(input.argsJson ?? {}),
  };

  const errors: string[] = [];
  const unknownFlags: string[] = [];

  for (const [flagName, raw] of Object.entries(input.flags)) {
    const spec = specByFlag.get(flagName);
    if (!spec) {
      unknownFlags.push(`--${flagName}`);
      continue;
    }
    const coerced = coerceScalar(raw, spec.type);
    if ('error' in coerced) {
      errors.push(`--${flagName}: ${coerced.error} (got "${String(raw)}")`);
      continue;
    }
    if (spec.enum && typeof coerced.value === 'string' && !spec.enum.includes(coerced.value)) {
      errors.push(`--${flagName}: must be one of ${spec.enum.join(', ')} (got "${coerced.value}")`);
      continue;
    }
    merged[spec.name] = coerced.value;
  }

  const missing = specs
    .filter((spec) => spec.required && merged[spec.name] === undefined)
    .map((spec) => `--${toKebab(spec.name)}`);

  if (unknownFlags.length > 0) {
    errors.push(`Unknown flag(s): ${unknownFlags.join(', ')}`);
  }
  if (missing.length > 0) {
    errors.push(`Missing required flag(s): ${missing.join(', ')}`);
  }

  return { args: merged, errors };
}

export interface ManifestSummary {
  toolCount: number;
  domains: ManifestDomainSpec[];
  builtins: string[];
}

const BUILTIN_COMMANDS = [
  'auth login',
  'auth status',
  'auth logout',
  'manifest',
  'doctor',
  'call',
  'mcp parity',
  'version',
  'help',
];

export function summarizeManifest(manifest: Manifest): ManifestSummary {
  return {
    toolCount: manifest.toolCount,
    domains: manifest.domains,
    builtins: manifest.builtins ?? BUILTIN_COMMANDS,
  };
}

export interface DomainCommandSummary {
  cmd: string;
  desc?: string;
  destructive: boolean;
}

export function summarizeDomain(manifest: Manifest, domain: string): DomainCommandSummary[] {
  return domainCommands(manifest, domain).map((t) => ({
    cmd: t.cmd,
    desc: t.desc,
    destructive: Boolean(t.destructive),
  }));
}
