// ─── BLOCK_ELEMENTS ──────────────────────────────────────────────────────────
// Source of truth for sub-element tabs in the style panel.
// Every entry's `key` MUST match a `getElementCSS(block.elementStyles, '<key>')`
// call in the block's render component. Missing keys = uneditable parts.
// Audited 2026-04-16 against all render files.
export const BLOCK_ELEMENTS: Record<string, { key: string; label: string }[]> = {
  hero: [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'subtitle', label: 'Subtitle' },
    { key: 'description', label: 'Description' },
    { key: 'cta', label: 'CTA Button' },
    { key: 'secondaryCta', label: 'Secondary CTA' },
  ],
  'hero-slideshow': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Slide Title' },
    { key: 'subtitle', label: 'Slide Subtitle' },
    { key: 'description', label: 'Slide Description' },
    { key: 'cta', label: 'Primary Button' },
    { key: 'secondaryCta', label: 'Secondary Button' },
    { key: 'statValue', label: 'Stat Value' },
    { key: 'statLabel', label: 'Stat Label' },
  ],
  marquee: [
    { key: '_block', label: 'Block' },
    { key: 'text', label: 'Text Items' },
    { key: 'image', label: 'Image Items' },
    { key: 'icon', label: 'Icon Items' },
  ],
  cta: [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'primaryButton', label: 'Primary Button' },
    { key: 'secondaryButton', label: '2nd Button' },
  ],
  'card-grid': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'card', label: 'Cards' },
    { key: 'cardTitle', label: 'Card Title' },
    { key: 'cardDescription', label: 'Card Text' },
    { key: 'cardIcon', label: 'Card Icon' },
    { key: 'cardImage', label: 'Card Image' },
    { key: 'cardLink', label: 'Card Link' },
  ],
  'flip-card-grid': [
    { key: '_block', label: 'Block' },
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'frontCard', label: 'Front Card' },
    { key: 'frontTitle', label: 'Front Title' },
    { key: 'frontSubtitle', label: 'Front Subtitle' },
    { key: 'frontIcon', label: 'Front Icon' },
    { key: 'backCard', label: 'Back Card' },
    { key: 'backText', label: 'Back Text' },
    { key: 'backLink', label: 'Back Link' },
  ],
  'metric-cards': [
    { key: '_block', label: 'Block' },
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'card', label: 'Card' },
    { key: 'value', label: 'Value' },
    { key: 'label', label: 'Label' },
    { key: 'institution', label: 'Institution' },
    { key: 'link', label: 'Link' },
  ],
  'logo-strip': [
    { key: '_block', label: 'Block' },
    { key: 'overline', label: 'Overline' },
    { key: 'logo', label: 'Logo' },
  ],
  stats: [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'statValue', label: 'Values' },
    { key: 'statLabel', label: 'Labels' },
  ],
  testimonial: [
    { key: '_block', label: 'Block' },
    { key: 'quote', label: 'Quote' },
    { key: 'quoteIcon', label: 'Quote Icon' },
    { key: 'author', label: 'Author' },
  ],
  'services-grid': [
    { key: '_block', label: 'Block' },
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'card', label: 'Card' },
    { key: 'serviceTitle', label: 'Service Title' },
    { key: 'serviceDescription', label: 'Service Text' },
    { key: 'serviceIcon', label: 'Service Icon' },
    { key: 'serviceImage', label: 'Service Image' },
    { key: 'bullet', label: 'Bullets' },
    { key: 'serviceLink', label: 'Service Link' },
  ],
  'featured-content': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'button', label: 'Button' },
    { key: 'statValue', label: 'Stat Value' },
    { key: 'statLabel', label: 'Stat Label' },
  ],
  accordion: [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'itemTitle', label: 'Item Titles' },
    { key: 'itemContent', label: 'Item Content' },
  ],
  quote: [
    { key: '_block', label: 'Block' },
    { key: 'quoteText', label: 'Quote' },
    { key: 'author', label: 'Author' },
  ],
  'product-detail': [
    { key: '_block', label: 'Block' },
    { key: 'productName', label: 'Product Name' },
    { key: 'price', label: 'Price' },
    { key: 'comparePrice', label: 'Compare Price' },
    { key: 'shortDescription', label: 'Description' },
    { key: 'badge', label: 'Sale Badge' },
    { key: 'optionLabel', label: 'Option Label' },
    { key: 'optionButton', label: 'Option Button' },
    { key: 'addToCartButton', label: 'Add to Cart' },
    { key: 'breadcrumb', label: 'Breadcrumb' },
    { key: 'sku', label: 'SKU / Tags' },
    { key: 'sectionTitle', label: 'Section Titles' },
    { key: 'gallery', label: 'Gallery' },
  ],
  'booking': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  'survey': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  'blog-posts': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
    { key: 'postTitle', label: 'Post Title' },
    { key: 'postExcerpt', label: 'Post Excerpt' },
  ],
  'bento-grid': [
    { key: '_block', label: 'Block' },
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Title' },
    { key: 'subtitle', label: 'Subtitle' },
    { key: 'cardTitle', label: 'Card Title' },
    { key: 'cardLead', label: 'Card Lead' },
  ],
  'booking-menu': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  'featured-products': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  gallery: [
    { key: '_block', label: 'Block' },
    { key: 'caption', label: 'Caption' },
  ],
  'product-grid': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'description', label: 'Description' },
  ],
  'store-banner': [
    { key: '_block', label: 'Block' },
    { key: 'title', label: 'Title' },
    { key: 'subtitle', label: 'Subtitle' },
    { key: 'button', label: 'Button' },
    { key: 'discountCode', label: 'Discount Code' },
  ],
  'team-showcase': [
    { key: '_block', label: 'Block' },
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Title' },
    { key: 'subtitle', label: 'Subtitle' },
    { key: 'memberName', label: 'Member Name' },
    { key: 'memberTitle', label: 'Member Title' },
    { key: 'memberBio', label: 'Member Bio' },
    { key: 'memberCredentials', label: 'Credentials' },
    { key: 'specialtyTag', label: 'Specialty Tag' },
  ],
  timeline: [
    { key: '_block', label: 'Block' },
    { key: 'overline', label: 'Overline' },
    { key: 'title', label: 'Title' },
    { key: 'subtitle', label: 'Subtitle' },
    { key: 'stepTitle', label: 'Step Title' },
    { key: 'stepDescription', label: 'Step Text' },
  ],
};
