/**
 * MCP tools — project custom fields.
 *
 * Split out of projects.ts rather than appended to it: that file is pinned at
 * 502 lines by the file-size budget ("god files may shrink, never grow"), and
 * kanban.ts — where the per-card half would otherwise sit — is already 1294.
 * Same shape as pathviz-coordination.ts, a sibling registrar of pathviz.ts.
 *
 * Field DEFINITIONS are project-scoped; VALUES hang off cards. Both live here
 * because they are one feature and share the ownership rules below.
 *
 * These exist so an agent can run the AI-native delivery pilot (autonomy tier,
 * risk score, human-touch estimate) with no schema migration —
 * project_custom_fields is the extension point that already ships, and only
 * the dimensions that actually get filled in ever need promoting to columns.
 */
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { and, asc, eq, inArray } from 'drizzle-orm';
import { db } from '@/lib/db';
import {
  projects,
  kanbanCards,
  projectCustomFields,
  cardCustomFieldValues,
} from '@/lib/db/schema';
import type { PortalMcpContext } from '@/lib/mcp-auth';
import { hasScope } from '@/lib/mcp-auth';
import { json, denied, requireScope, revalidateForWrite } from '../types';

const FIELD_KINDS = ['text', 'number', 'date', 'select', 'multi_select', 'url', 'checkbox'] as const;

/** Mirrors the REST route's slugify so keys generated by either path match. */
function slugifyKey(input: string): string {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 60) || 'field';
}

export function registerProjectCustomFieldTools(server: McpServer, ctx: PortalMcpContext): void {
  const clientId = ctx.client.id;

  async function authorizeProject(projectId: number) {
    const [proj] = await db.select({ id: projects.id }).from(projects)
      .where(and(eq(projects.id, projectId), eq(projects.clientId, clientId))).limit(1);
    return proj ?? null;
  }

  async function authorizeCard(cardId: number) {
    const [card] = await db.select({ id: kanbanCards.id, projectId: kanbanCards.projectId })
      .from(kanbanCards).where(eq(kanbanCards.id, cardId)).limit(1);
    if (!card) return null;
    // Tenancy is enforced through the card's PROJECT — kanban_cards has no
    // clientId column of its own.
    return (await authorizeProject(card.projectId)) ? card : null;
  }

  hasScope(ctx.scopes, 'projects:read') && server.registerTool(
    'project_custom_fields_list',
    {
      title: "List a project's custom field definitions",
      description: 'List the custom fields defined on a project (key, name, kind, required, options). These are definitions, not per-card values — use kanban_card_custom_fields_get for those.',
      inputSchema: { projectId: z.coerce.number() },
    },
    async ({ projectId }) => {
      if (!requireScope(ctx, 'projects:read')) return denied('projects:read');
      if (!(await authorizeProject(projectId))) return json({ error: 'Project not found' });
      const rows = await db.select({
        id: projectCustomFields.id,
        key: projectCustomFields.key,
        name: projectCustomFields.name,
        kind: projectCustomFields.kind,
        required: projectCustomFields.required,
        options: projectCustomFields.options,
        order: projectCustomFields.order,
      }).from(projectCustomFields)
        .where(eq(projectCustomFields.projectId, projectId))
        .orderBy(asc(projectCustomFields.order), asc(projectCustomFields.id));
      return json(rows);
    }
  );

  hasScope(ctx.scopes, 'projects:write') && server.registerTool(
    'project_custom_fields_create',
    {
      title: 'Define a custom field on a project',
      description: 'Add a custom field definition to a project. The key is derived from the name and de-duplicated automatically. `options` applies only to select / multi_select.',
      inputSchema: {
        projectId: z.coerce.number(),
        name: z.string().min(1).max(100),
        kind: z.enum(FIELD_KINDS),
        required: z.boolean().optional(),
        options: z.array(z.string()).optional(),
      },
    },
    async ({ projectId, name, kind, required, options }) => {
      if (!requireScope(ctx, 'projects:write')) return denied('projects:write');
      if (!(await authorizeProject(projectId))) return json({ error: 'Project not found' });

      // The key is DERIVED, never taken from input: it is the stable API handle
      // and must stay unique per project even when two fields share a display
      // name. A unique index backs it, so a collision would throw rather than
      // quietly overwrite.
      const existing = await db.select({ key: projectCustomFields.key, order: projectCustomFields.order })
        .from(projectCustomFields).where(eq(projectCustomFields.projectId, projectId));
      const used = new Set(existing.map((e) => e.key));
      const base = slugifyKey(name);
      let key = base;
      let n = 2;
      while (used.has(key)) key = `${base}_${n++}`;

      const nextOrder = existing.length === 0 ? 0 : Math.max(...existing.map((e) => e.order)) + 1;

      const [row] = await db.insert(projectCustomFields).values({
        projectId,
        key,
        name: name.trim().slice(0, 100),
        kind,
        required: required ?? false,
        // Options are meaningless off a select. Storing them anyway would let a
        // later kind change silently resurrect stale choices.
        options: (kind === 'select' || kind === 'multi_select')
          ? (options ?? []).filter((o) => typeof o === 'string').slice(0, 50)
          : [],
        order: nextOrder,
        createdBy: ctx.userId,
      }).returning();
      revalidateForWrite('portal');
      return json({ id: row.id, key: row.key, name: row.name, kind: row.kind });
    }
  );

  hasScope(ctx.scopes, 'projects:write') && server.registerTool(
    'project_custom_fields_delete',
    {
      title: 'Delete a project custom field',
      description: 'Remove a custom field definition. Every card value for that field is deleted with it (FK cascade) — this is not reversible.',
      inputSchema: { projectId: z.coerce.number(), fieldId: z.coerce.number() },
    },
    async ({ projectId, fieldId }) => {
      if (!requireScope(ctx, 'projects:write')) return denied('projects:write');
      if (!(await authorizeProject(projectId))) return json({ error: 'Project not found' });
      // Re-scoped by projectId as well as id: a field belonging to another
      // project of the SAME client must not be deletable from here.
      const [row] = await db.delete(projectCustomFields)
        .where(and(eq(projectCustomFields.id, fieldId), eq(projectCustomFields.projectId, projectId)))
        .returning({ id: projectCustomFields.id, key: projectCustomFields.key });
      if (!row) return json({ error: 'Field not found on this project' });
      revalidateForWrite('portal');
      return json({ deleted: row.id, key: row.key });
    }
  );

  hasScope(ctx.scopes, 'projects:read') && server.registerTool(
    'kanban_card_custom_fields_get',
    {
      title: "Get a card's custom field values",
      description: "Return every custom field defined on the card's project, each with this card's value (null when unset).",
      inputSchema: { cardId: z.coerce.number() },
    },
    async ({ cardId }) => {
      if (!requireScope(ctx, 'projects:read')) return denied('projects:read');
      const card = await authorizeCard(cardId);
      if (!card) return json({ error: 'Card not found' });

      const fields = await db.select({
        id: projectCustomFields.id,
        key: projectCustomFields.key,
        name: projectCustomFields.name,
        kind: projectCustomFields.kind,
      }).from(projectCustomFields)
        .where(eq(projectCustomFields.projectId, card.projectId))
        .orderBy(asc(projectCustomFields.order), asc(projectCustomFields.id));

      const values = await db.select({
        fieldId: cardCustomFieldValues.fieldId,
        value: cardCustomFieldValues.value,
      }).from(cardCustomFieldValues).where(eq(cardCustomFieldValues.cardId, cardId));

      const byField = new Map(values.map((v) => [v.fieldId, v.value]));
      return json(fields.map((f) => ({ ...f, value: byField.get(f.id) ?? null })));
    }
  );

  hasScope(ctx.scopes, 'projects:write') && server.registerTool(
    'kanban_card_custom_fields_set',
    {
      title: 'Set custom field values on a card',
      description: "Upsert one or more custom field values on a card. Every fieldId must belong to the card's own project.",
      inputSchema: {
        cardId: z.coerce.number(),
        values: z.array(z.object({ fieldId: z.coerce.number(), value: z.unknown() })).min(1).max(50),
      },
    },
    async ({ cardId, values }) => {
      if (!requireScope(ctx, 'projects:write')) return denied('projects:write');
      const card = await authorizeCard(cardId);
      if (!card) return json({ error: 'Card not found' });

      // CROSS-PROJECT POISONING GUARD. card_custom_field_values holds only
      // (cardId, fieldId) — no project column — and both are caller-supplied.
      // One client legitimately owns many projects, so tenancy scoping alone
      // lets a caller with a real card in project A write onto project B's
      // field definition. Same client on both sides; only this check stops it.
      const ids = [...new Set(values.map((v) => v.fieldId))];
      const owned = await db.select({ id: projectCustomFields.id })
        .from(projectCustomFields)
        .where(and(
          eq(projectCustomFields.projectId, card.projectId),
          inArray(projectCustomFields.id, ids),
        ));
      const ownedIds = new Set(owned.map((f) => f.id));
      const stray = ids.find((id) => !ownedIds.has(id));
      if (stray !== undefined) return json({ error: `Field ${stray} is not on this card's project` });

      for (const v of values) {
        await db.insert(cardCustomFieldValues).values({
          cardId,
          fieldId: v.fieldId,
          value: v.value as typeof cardCustomFieldValues.$inferInsert['value'],
        }).onConflictDoUpdate({
          target: [cardCustomFieldValues.cardId, cardCustomFieldValues.fieldId],
          set: {
            value: v.value as typeof cardCustomFieldValues.$inferInsert['value'],
            updatedAt: new Date(),
          },
        });
      }
      revalidateForWrite('portal');
      return json({ cardId, updated: values.length });
    }
  );
}
